name: Test

env:
  PLUGIN_NAME: ${{ github.event.repository.name }}

on:
  push:
    branches:
      - main
      - next
  pull_request:
    branches:
      - main
      - next
  workflow_dispatch:

jobs:
  test:
    name: redmine:${{ matrix.redmine_version }} ruby:${{ matrix.ruby_version }} db:${{ matrix.db }}
    runs-on: ubuntu-24.04

    strategy:
      fail-fast: false
      matrix:
        redmine_version: [5.1-stable, 6.0-stable, master]
        ruby_version: ['3.1', '3.2', '3.3']
        db: ['postgres:14', 'sqlite3']
        exclude:
          - redmine_version: master
            ruby_version: '3.1'

    steps:
      - name: Setup Redmine
        uses: hidakatsuya/action-setup-redmine@v2
        with:
          repository: redmine/redmine
          version: ${{ matrix.redmine_version }}
          ruby-version: ${{ matrix.ruby_version }}
          database: ${{ matrix.db }}
          path: redmine

      - name: Checkout Plugin
        uses: actions/checkout@v4
        with:
          path: redmine/plugins/${{ env.PLUGIN_NAME }}

      - name: Install Ruby dependencies
        working-directory: redmine
        run: |
          bundle config set --local without 'development'
          bundle install --jobs=4 --retry=3

      - name: Run Redmine rake tasks
        working-directory: redmine
        run: |
          bundle exec rake generate_secret_token
          bundle exec rake db:create db:migrate redmine:plugins:migrate

      - name: Zeitwerk check
        working-directory: redmine
        run: |
          if grep -q zeitwerk config/application.rb ; then
            bundle exec rake zeitwerk:check
          fi
        shell: bash

      - name: Run plugin tests
        working-directory: redmine
        run: |
          bundle exec rake redmine:plugins:test:units NAME=${{ env.PLUGIN_NAME }} RUBYOPT="-W0"
          bundle exec rake redmine:plugins:test:integration NAME=${{ env.PLUGIN_NAME }} RUBYOPT="-W0"

      - name: Run uninstall test
        working-directory: redmine
        run: bundle exec rake redmine:plugins:migrate NAME=${{ env.PLUGIN_NAME }} VERSION=0
